# base properties
api.baseUrl = http://localhost:4111/api
version = /v1

# services properties
api.accounts = /accounts
api.admin = /admin
api.authentication = /auth
api.customer = /customer

# UI property
ui.remote = http://localhost:4444/wd/hub
ui.baseUrl = http://192.168.0.137:3000
ui.browser = chrome
ui.browserSize = 1920x1080