# Format: RequestClass=ResponseClass=ResponseClass:field1=field1Response,field2=field2Response

CreateUserRequestDTO=CreateUserResponseDTO:username=username,role=role
UpdateProfileRequestDTO=UpdateProfileResponseDTO:name=user.name
TransferResponseDTO=TransferResponseDTO:status=status,message=message,amount=amount,senderAccountId=senderAccountId,receiverAccountId=receiverAccountId,fraudRiskScore=fraudRiskScore,fraudReason=fraudReason,requiresManualReview=requiresManualReview,requiresVerification=requiresVerification